---
to: <%= absPath %>/Readme.md
---
# Readme for Module Component <%= component_name %>

The template Component <%= component_name %> was generated by Hygen plugin

THis is index <%= lower_name %> of component <%= component_name %>

## files

```text
  /<%= absPath %>/<%= component_name %>.jsx
  /<%= absPath %>/<%= component_name %>.module.css
  /<%= absPath %>/index.js
  /<%= absPath %>/Readme.md
```

## file list

>
> 1. /<%= absPath %>/<%= component_name %>.jsx
> 2. /<%= absPath %>/<%= component_name %>.module.css
> 3. /<%= absPath %>/index.js
> 4. /<%= absPath %>/Readme.md
>
