---
to: <%= absPath %>/Readme.md
---
# Readme for Module Component <%= component_name %>

The template Component <%= component_name %> was generated by Hygen plugin

THis is index <%= lower_name %> of component <%= component_name %>

## files

```text
  ./<%= absPath %>/<%= component_name %>.jsx
  ./<%= absPath %>/<%= component_name %>.module.css
  ./<%= absPath %>/index.js
  ./<%= absPath %>/Readme.md
```

## generated file list

>
> 1. [<%= component_name %>.jsx]<./<%= absPath %>/<%= component_name %>.jsx>
> 2. [<%= component_name %>.module.css]<./<%= absPath %>/<%= component_name %>.module.css>
> 3. [index.js]<./<%= absPath %>/index.js>
> 4. [Readme.md]<./<%= absPath %>/Readme.md>
